// scripts/fixtures/react-app.ts
// The app scripts/check-react.ts renders on the server and hydrates in the
// browser, with React 18 and with React 19. Built against dist/react.
import * as React from "react";
import {
  Button, Checkbox, List, ListItem, NavigationRail, NavigationRailItem, Progress, Radio, Radios, Slider, Switch, Tab, Tabs,
  Textfield,
} from "../../dist/react/index.js";
import type { SwitchElement } from "../../dist/elements/index.js";
import { Chip, Chips } from "../../dist/react/index.js";
import { Select, SelectOption } from "../../dist/react/index.js";
import { Dialog } from "../../dist/react/index.js";
import { Search, SearchSuggestion } from "../../dist/react/index.js";

const h = React.createElement;
const ICON = '<svg viewBox="0 0 24 24"><path d="M4 4h16v16H4z"/></svg>';
// The suggestions a search offers, filtered by the query as the user types.
const FRUITS = ["Apple", "Apricot", "Banana"];
// JSX accepts data-* on any element; createElement with an object literal does not.
const dataTest = { "data-test": "1" } as React.HTMLAttributes<HTMLElement>;

type Log = Array<{ id: string; detail: unknown }>;
type Api = {
  log: Log;
  submits: number;
  setExtra: (v: boolean) => void;
  setOrder: (v: string[]) => void;
  setShow: (v: boolean) => void;
  setProgress: (v: number) => void;
  setDialog: (v: boolean) => void;
  switchRef: React.RefObject<SwitchElement | null>;
};

export const App = (): React.ReactElement => {
  const [controlled, setControlled] = React.useState(false);
  const [agreed, setAgreed] = React.useState(false);
  const [level, setLevel] = React.useState(50);
  const [text, setText] = React.useState("");
  const [size, setSize] = React.useState<string | null>("m");
  const [diet, setDiet] = React.useState<string | string[] | null>(["veg"]);
  const [tab, setTab] = React.useState<string | null>("t2");
  const [destination, setDestination] = React.useState<string | null>("inbox");
  const [extra, setExtra] = React.useState(false);
  const [order, setOrder] = React.useState(["a", "b"]);
  const [show, setShow] = React.useState(true);
  const [progress, setProgress] = React.useState(30);
  const [fruit, setFruit] = React.useState<string | null>("b");
  const [pet, setPet] = React.useState<string | null>("cat");
  const [dialog, setDialog] = React.useState(false);
  const [query, setQuery] = React.useState("ap");
  const switchRef = React.useRef<SwitchElement | null>(null);
  const api = React.useRef<Api | null>(null);

  React.useEffect(() => {
    const w = window as unknown as { api?: Api };
    api.current = w.api ?? { log: [], submits: 0, setExtra, setOrder, setShow, setProgress, setDialog, switchRef };
    w.api = api.current;
  }, []);
  const log = (id: string) => (event: CustomEvent<unknown>): void => {
    api.current?.log.push({ id, detail: event.detail });
  };

  return h(
    "main",
    null,
    h(
      "form",
      {
        id: "f",
        onSubmit: (e: React.FormEvent) => {
          e.preventDefault();
          if (api.current) api.current.submits++;
        },
      },
      h(Switch, { id: "u", name: "u", defaultChecked: true, onChange: log("u"), ref: switchRef }, "Uncontrolled"),
      h(Switch, { id: "c", checked: controlled, onChange: (e) => setControlled(e.detail.checked) }, "Controlled"),
      h(Switch, { id: "l", checked: false, onChange: log("l") }, "Locked"),
      h(Switch, { id: "d", disabled: true, supportingText: "Unavailable" }, "Disabled"),
      h(Button, { id: "b", type: "submit", variant: "filled", className: "save", ...dataTest }, "Save")
    ),
    h(
      Tabs,
      { id: "t", value: tab, onChange: (e) => setTab(e.detail.value) },
      h(Tab, { value: "t1" }, "Flights"),
      h(Tab, { value: "t2" }, "Trips"),
      extra ? h(Tab, { value: "t3" }, "Hotels") : null
    ),
    h("output", { id: "tab" }, tab),
    h("output", { id: "controlled" }, String(controlled)),
    h(Progress, { id: "pg", value: progress, ariaLabel: "Uploading" }),
    h(Checkbox, { id: "cb", checked: agreed, onChange: (e) => setAgreed(e.detail.checked) }, "Agree"),
    h("output", { id: "agreed" }, String(agreed)),
    h(Slider, { id: "sl", ariaLabel: "Level", value: level, onChange: (e) => setLevel(e.detail.value) }),
    h("output", { id: "level" }, String(level)),
    h(Textfield, { id: "tf", label: "Name", value: text, onInput: (e) => setText(e.detail.value) }),
    h("output", { id: "text" }, text),
    h(
      Radios,
      { id: "rd", value: size, ariaLabel: "Size", onChange: (e) => setSize(e.detail.value) },
      h(Radio, { value: "s" }, "Small"),
      h(Radio, { value: "m" }, "Medium"),
      h(Radio, { value: "l" }, "Large")
    ),
    h("output", { id: "size" }, size),
    h(
      NavigationRail,
      { id: "nr", value: destination, ariaLabel: "Main", onChange: (e) => setDestination(e.detail.value) },
      h(NavigationRailItem, { value: "inbox", icon: ICON }, "Inbox"),
      h(NavigationRailItem, { value: "sent", icon: ICON }, "Sent"),
      h(NavigationRailItem, { value: "starred", icon: ICON }, "Starred")
    ),
    h("output", { id: "destination" }, destination),
    h(
      Chips,
      { id: "ck", ariaLabel: "Diet", value: diet, onChange: (e) => setDiet(e.detail.value) },
      h(Chip, { value: "veg" }, "Vegetarian"),
      h(Chip, { value: "gf" }, "Gluten free")
    ),
    h("output", { id: "diet" }, String(diet)),
    h(
      List,
      { id: "li", value: fruit, ariaLabel: "Fruits", onChange: (e) => setFruit(e.detail.value) },
      h(ListItem, { value: "a" }, "Apple"),
      h(ListItem, { value: "b" }, "Banana"),
      h(ListItem, { value: "c" }, "Cherry")
    ),
    h("output", { id: "fruit" }, fruit),
    h(
      Select,
      { id: "se", label: "Pet", value: pet, onChange: (e) => setPet(e.detail.value) },
      h(SelectOption, { value: "cat" }, "Cat"),
      h(SelectOption, { value: "dog" }, "Dog")
    ),
    h("output", { id: "pet" }, pet),
    // Controlled: Escape closes the dialog, and onClose puts the state in step
    h(
      Dialog,
      { id: "dg", open: dialog, onClose: () => setDialog(false) },
      h("span", { slot: "headline" }, "Discard draft?"),
      "Your changes will be lost."
    ),
    h("output", { id: "dialog" }, String(dialog)),
    // Controlled, its suggestions replaced as the query changes
    h(
      Search,
      { id: "sq", ariaLabel: "Query", value: query, onInput: (e) => setQuery(e.detail.value), onSelect: (e) => setQuery(e.detail.value) },
      ...FRUITS.filter((f) => f.toLowerCase().includes(query.toLowerCase())).map((f) =>
        h(SearchSuggestion, { key: f, value: f.toLowerCase() }, f)
      )
    ),
    h("output", { id: "query" }, query),
    ...order.map((key) => h(Switch, { key, id: `o${key}` }, `Order ${key}`)),
    show ? h(Switch, { id: "gone" }, "Gone") : null,
    // Mounted in the browser after the element is defined: React 19 then
    // assigns same-named props to element properties.
    extra ? h(Switch, { id: "late", defaultChecked: true, disabled: true }, "Late") : null
  );
};

// scripts/fixtures/solid-app.tsx
// The app scripts/check-solid.ts renders on the server and hydrates in the
// browser. Solid JSX, compiled by babel-preset-solid as a Solid app's build
// compiles it. Built against dist/solid.
import { createSignal, For, onMount, Show } from "solid-js";
import {
  Button, Checkbox, List, ListItem, NavigationRail, NavigationRailItem, Progress, Radio, Radios, Slider, Switch, Tab, Tabs,
  Textfield,
} from "../../dist/solid/index.js";
import type { SwitchElement } from "../../dist/elements/index.js";
import { Chip, Chips } from "../../dist/solid/index.js";
import { Select, SelectOption } from "../../dist/solid/index.js";
import { Dialog } from "../../dist/solid/index.js";
import { Search, SearchSuggestion } from "../../dist/solid/index.js";

const ICON = '<svg viewBox="0 0 24 24"><path d="M4 4h16v16H4z"/></svg>';
// The suggestions a search offers, filtered by the query as the user types.
const FRUITS = ["Apple", "Apricot", "Banana"];

export const App = () => {
  const log: Array<{ id: string; detail: unknown }> = [];
  let submits = 0;
  const [controlled, setControlled] = createSignal(false);
  const [agreed, setAgreed] = createSignal(false);
  const [level, setLevel] = createSignal(50);
  const [text, setText] = createSignal("");
  const [size, setSize] = createSignal<string | null>("m");
  const [diet, setDiet] = createSignal<string | string[] | null>(["veg"]);
  const [tab, setTab] = createSignal<string | null>("t2");
  const [destination, setDestination] = createSignal<string | null>("inbox");
  const [extra, setExtra] = createSignal(false);
  const [order, setOrder] = createSignal(["a", "b"]);
  const [show, setShow] = createSignal(true);
  const [progress, setProgress] = createSignal(30);
  const [fruit, setFruit] = createSignal<string | null>("b");
  const [pet, setPet] = createSignal<string | null>("cat");
  const [dialog, setDialog] = createSignal(false);
  const [query, setQuery] = createSignal("ap");
  let switchRef: SwitchElement | undefined;
  const record = (id: string) => (event: CustomEvent<unknown>) => log.push({ id, detail: event.detail });

  onMount(() => {
    (window as unknown as { api: unknown }).api = {
      log,
      get submits() { return submits; },
      setControlled, setExtra, setOrder, setShow, setProgress, setDialog,
      element: () => switchRef,
    };
  });

  return (
    <main>
      <form id="f" onSubmit={(e) => { e.preventDefault(); submits++; }}>
        <Switch id="u" name="u" defaultChecked onChange={record("u")} ref={switchRef}>Uncontrolled</Switch>
        <Switch id="c" checked={controlled()} onChange={(e) => setControlled(e.detail.checked)}>Controlled</Switch>
        <Switch id="d" disabled supportingText="Unavailable">Disabled</Switch>
        <Button id="b" type="submit" variant="filled" class="save" data-test="1">Save</Button>
      </form>
      <Tabs id="t" value={tab()} onChange={(e) => setTab(e.detail.value)}>
        <Tab value="t1">Flights</Tab>
        <Tab value="t2">Trips</Tab>
        <Show when={extra()}><Tab value="t3">Hotels</Tab></Show>
      </Tabs>
      <output id="tab">{String(tab())}</output>
      <output id="controlled">{String(controlled())}</output>
      <Progress id="pg" value={progress()} ariaLabel="Uploading" />
      <Checkbox id="cb" checked={agreed()} onChange={(e) => setAgreed(e.detail.checked)}>Agree</Checkbox>
      <output id="agreed">{String(agreed())}</output>
      <Slider id="sl" ariaLabel="Level" value={level()} onChange={(e) => setLevel(e.detail.value)} />
      <output id="level">{String(level())}</output>
      <Textfield id="tf" label="Name" value={text()} onInput={(e) => setText(e.detail.value)} />
      <output id="text">{text()}</output>
      <Radios id="rd" ariaLabel="Size" value={size()} onChange={(e) => setSize(e.detail.value)}>
        <Radio value="s">Small</Radio>
        <Radio value="m">Medium</Radio>
        <Radio value="l">Large</Radio>
      </Radios>
      <output id="size">{String(size())}</output>
      <NavigationRail id="nr" ariaLabel="Main" value={destination()} onChange={(e) => setDestination(e.detail.value)}>
        <NavigationRailItem value="inbox" icon={ICON}>Inbox</NavigationRailItem>
        <NavigationRailItem value="sent" icon={ICON}>Sent</NavigationRailItem>
        <NavigationRailItem value="starred" icon={ICON}>Starred</NavigationRailItem>
      </NavigationRail>
      <output id="destination">{String(destination())}</output>
      <Chips id="ck" ariaLabel="Diet" value={diet()} onChange={(e) => setDiet(e.detail.value)}>
        <Chip value="veg">Vegetarian</Chip>
        <Chip value="gf">Gluten free</Chip>
      </Chips>
      <output id="diet">{String(diet())}</output>
      <List id="li" ariaLabel="Fruits" value={fruit()} onChange={(e) => setFruit(e.detail.value)}>
        <ListItem value="a">Apple</ListItem>
        <ListItem value="b">Banana</ListItem>
        <ListItem value="c">Cherry</ListItem>
      </List>
      <output id="fruit">{String(fruit())}</output>
      <Select id="se" label="Pet" value={pet()} onChange={(e) => setPet(e.detail.value)}>
        <SelectOption value="cat">Cat</SelectOption>
        <SelectOption value="dog">Dog</SelectOption>
      </Select>
      <output id="pet">{String(pet())}</output>
      {/* Controlled: Escape closes the dialog, and onClose puts the state in step */}
      <Dialog id="dg" open={dialog()} onClose={() => setDialog(false)}>
        <span slot="headline">Discard draft?</span>Your changes will be lost.
      </Dialog>
      <output id="dialog">{String(dialog())}</output>
      {/* Controlled, its suggestions replaced as the query changes */}
      <Search id="sq" ariaLabel="Query" value={query()} onInput={(e) => setQuery(e.detail.value)} onSelect={(e) => setQuery(e.detail.value)}>
        <For each={FRUITS.filter((f) => f.toLowerCase().includes(query().toLowerCase()))}>
          {(f) => <SearchSuggestion value={f.toLowerCase()}>{f}</SearchSuggestion>}
        </For>
      </Search>
      <output id="query">{query()}</output>
      <For each={order()}>{(key) => <Switch id={`o${key}`}>Order {key}</Switch>}</For>
      <Show when={show()}><Switch id="gone">Gone</Switch></Show>
      {/* Mounted in the browser after the element is defined: Solid writes a
          key the element has as a property. */}
      <Show when={extra()}><Switch id="late" defaultChecked disabled>Late</Switch></Show>
    </main>
  );
};
