// scripts/fixtures/solid-app.tsx
// The app scripts/check-solid.ts renders on the server and hydrates in the
// browser. Solid JSX, compiled by babel-preset-solid as a Solid app's build
// compiles it. Built against dist/solid.
import { createSignal, For, onMount, Show } from "solid-js";
import { Button, Checkbox, Progress, Slider, Switch, Tab, Tabs } from "../../dist/solid/index.js";
import type { SwitchElement } from "../../dist/elements/index.js";

export const App = () => {
  const log: Array<{ id: string; detail: unknown }> = [];
  let submits = 0;
  const [controlled, setControlled] = createSignal(false);
  const [agreed, setAgreed] = createSignal(false);
  const [level, setLevel] = createSignal(50);
  const [tab, setTab] = createSignal<string | null>("t2");
  const [extra, setExtra] = createSignal(false);
  const [order, setOrder] = createSignal(["a", "b"]);
  const [show, setShow] = createSignal(true);
  const [progress, setProgress] = createSignal(30);
  let switchRef: SwitchElement | undefined;
  const record = (id: string) => (event: CustomEvent<unknown>) => log.push({ id, detail: event.detail });

  onMount(() => {
    (window as unknown as { api: unknown }).api = {
      log,
      get submits() { return submits; },
      setControlled, setExtra, setOrder, setShow, setProgress,
      element: () => switchRef,
    };
  });

  return (
    <main>
      <form id="f" onSubmit={(e) => { e.preventDefault(); submits++; }}>
        <Switch id="u" name="u" defaultChecked onChange={record("u")} ref={switchRef}>Uncontrolled</Switch>
        <Switch id="c" checked={controlled()} onChange={(e) => setControlled(e.detail.checked)}>Controlled</Switch>
        <Switch id="d" disabled supportingText="Unavailable">Disabled</Switch>
        <Button id="b" type="submit" variant="filled" class="save" data-test="1">Save</Button>
      </form>
      <Tabs id="t" value={tab()} onChange={(e) => setTab(e.detail.value)}>
        <Tab value="t1">Flights</Tab>
        <Tab value="t2">Trips</Tab>
        <Show when={extra()}><Tab value="t3">Hotels</Tab></Show>
      </Tabs>
      <output id="tab">{String(tab())}</output>
      <output id="controlled">{String(controlled())}</output>
      <Progress id="pg" value={progress()} ariaLabel="Uploading" />
      <Checkbox id="cb" checked={agreed()} onChange={(e) => setAgreed(e.detail.checked)}>Agree</Checkbox>
      <output id="agreed">{String(agreed())}</output>
      <Slider id="sl" ariaLabel="Level" value={level()} onChange={(e) => setLevel(e.detail.value)} />
      <output id="level">{String(level())}</output>
      <For each={order()}>{(key) => <Switch id={`o${key}`}>Order {key}</Switch>}</For>
      <Show when={show()}><Switch id="gone">Gone</Switch></Show>
      {/* Mounted in the browser after the element is defined: Solid writes a
          key the element has as a property. */}
      <Show when={extra()}><Switch id="late" defaultChecked disabled>Late</Switch></Show>
    </main>
  );
};

// scripts/fixtures/svelte-app.svelte
<!-- The app scripts/check-svelte.ts renders on the server and hydrates in the
     browser. Built against dist/svelte. -->
<script lang="ts">
  import { onMount } from "svelte";
  import { Button, Checkbox, Progress, Slider, Switch, Tab, Tabs, Textfield } from "../../dist/svelte/index.js";

  type Log = Array<{ id: string; detail: unknown }>;
  const log: Log = [];
  let submits = 0;
  let bound = $state(false);
  let agreed = $state(false);
  let level = $state(50);
  let text = $state("");
  let tab = $state<string | null>("t2");
  let extra = $state(false);
  let order = $state(["a", "b"]);
  let show = $state(true);
  let progress = $state(30);

  const record = (id: string) => (event: CustomEvent<unknown>) => log.push({ id, detail: event.detail });

  onMount(() => {
    (window as unknown as { api: unknown }).api = {
      log,
      get submits() { return submits; },
      setBound: (v: boolean) => (bound = v),
      setExtra: (v: boolean) => (extra = v),
      setOrder: (v: string[]) => (order = v),
      setShow: (v: boolean) => (show = v),
      setProgress: (v: number) => (progress = v),
    };
  });
</script>

<main>
  <form id="f" onsubmit={(e) => { e.preventDefault(); submits++; }}>
    <Switch id="u" name="u" defaultChecked onchange={record("u")}>Uncontrolled</Switch>
    <Switch id="m" bind:checked={bound}>Bound</Switch>
    <Switch id="d" disabled supportingText="Unavailable">Disabled</Switch>
    <Button id="b" type="submit" variant="filled" class="save" data-test="1">Save</Button>
  </form>
  <Tabs id="t" bind:value={tab}>
    <Tab value="t1">Flights</Tab>
    <Tab value="t2">Trips</Tab>
    {#if extra}<Tab value="t3">Hotels</Tab>{/if}
  </Tabs>
  <output id="tab">{String(tab)}</output>
  <output id="bound">{String(bound)}</output>
  <Progress id="pg" value={progress} ariaLabel="Uploading" />
  <Checkbox id="cb" bind:checked={agreed}>Agree</Checkbox>
  <output id="agreed">{String(agreed)}</output>
  <Slider id="sl" ariaLabel="Level" bind:value={level} />
  <output id="level">{String(level)}</output>
  <Textfield id="tf" label="Name" bind:value={text} />
  <output id="text">{text}</output>
  {#each order as key (key)}<Switch id={`o${key}`}>Order {key}</Switch>{/each}
  {#if show}<Switch id="gone">Gone</Switch>{/if}
  <!-- Mounted in the browser after the element is defined: Svelte writes a
       key the element has as a property. -->
  {#if extra}<Switch id="late" defaultChecked disabled>Late</Switch>{/if}
</main>
